### ISSUE TITLE
write file issue

### ISSUE THREAD

**Issue by mushan09** [zbhno37/srwe#1]
i used this code to train my word2vec model,but when i load a binary file from my disk, i meet some problem.  The file trained by google word2vec tools(C vecsion) is OK.
the main load code is like this:
    def _from_word2vec_binary(fname,vocab = None):
        with _open(fname, 'rb') as fin:
            words = []
            index = []
            header = fin.readline()
            print header
            vocab_size, layer1_size = list(map(int, header.split()))  # throws for invalid file format
            logger.info("Loading #{} words with {} dim".format(vocab_size, layer1_size))
            vectors = np.zeros((vocab_size, layer1_size), dtype=np.float32)
            binary_len = np.dtype("float32").itemsize * layer1_size
            for line_no in range(vocab_size):
                # mixed text and binary: read text first, then binary
                word = []
                while True:
                    ch = fin.read(1)
                    #import chardet
                    #print chardet.detect(ch)
                    if ch == b' ':
                        break
                    if ch != b'\n':  # ignore newlines in front of words (some binary files have newline, some don't)
                        word.append(ch)
it seems that the encoding has something wrong  with encoding?

**Comment by zbhno37** [comment]
is it my codes?
